name: React App Github Deploy

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-lates

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: install & build
        run: npm i && npm run build
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: dist